blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("notes.urls")),
    path('thanosss/', admin.site.urls),
    path("members/", include("members.urls")),
    path('members/', include("django.contrib.auth.urls")),
]

blog/members/urls.py
from . import views
from django.urls import path

app_name = 'members'
urlpatterns = [
	path("login/", views.login_user, name="login"),
]

blog/notes/urls.py
from . import views
from django.urls import path

app_name = 'notes'
urlpatterns = [
	path("", views.index, name="index"),
	path("blog/<blog_id>", views.details, name="show-details"),
]

blog/members/models.py
from django.db import models

# Create your models here.

blog/notes/models.py
from django.db import models
from django.utils import timezone
import datetime

class Blog(models.Model):
	title = models.CharField(max_length=100)
	blog = models.TextField(blank=False)
	description = models.CharField(max_length=500, default='No Description Available')
	pub_date = models.DateField("Date Published")

	def __str__(self):
		return self.title

	def was_published_recently(self):
		return self.pub_date >= timezone.now()
datetime.timedelta(days=1)

blog/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect("/")
		else:
			messages.success(request, ("There Was A Error Logging in. Try Again..."))
			return redirect('login')
	else:
		return render(request, "members/login.html", {})

blog/notes/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required

@login_required(login_url="/members/login/")
def index(request):
	latest_blog = Blog.objects.order_by('-pub_date')
	context = {
		"latest_blog": latest_blog,
	}
	return render(request, "notes/index.html", context)

@login_required(login_url="/members/login/")
def details(request, blog_id):
	try:
		blog = Blog.objects.get(pk=blog_id)
		return render(request, "notes/blog.html", {"blog": blog})
	except Blog.DoesNotExist:
		raise Http404("Server Fucked Up")

blog/members/templates/members/login.html
{% extends "notes/base.html" %}
{% block content %}
	<title>Login</title>
	<div class="contianer">
		<center>
			<h1>Login</h1>
		</center>
		<div class="container">
				<form action="" method="POST">
					{% csrf_token %}
					<div class="form-group">
					    <label for="exampleInputEmail1">Username</label>
					    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter email" required>
					</div>
					<div class="form-group">
					    <label for="exampleInputPassword1">Password</label>
					    <input type="password" class="form-control" name="password" placeholder="Password" required>
					</div>
					<br/>
					<center>
						<button type="submit" class="btn btn-primary">Submit</button>
					</center>
				</form>
		</div>
	</div>
{% endblock %}

blog/notes/templates/notes/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
		<nav class="navbar bg-light">
		  <div class="container-fluid">
		    <a class="navbar-brand" href="/">
		      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cpu" viewBox="0 0 16 16">
			  <path d="M5 0a.5.5 0 0 1 .5.5V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2A2.5 2.5 0 0 1 14 4.5h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14a2.5 2.5 0 0 1-2.5 2.5v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14A2.5 2.5 0 0 1 2 11.5H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2A2.5 2.5 0 0 1 4.5 2V.5A.5.5 0 0 1 5 0zm-.5 3A1.5 1.5 0 0 0 3 4.5v7A1.5 1.5 0 0 0 4.5 13h7a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 11.5 3h-7zM5 6.5A1.5 1.5 0 0 1 6.5 5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3zM6.5 6a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
				</svg>
		      Munseer
		    </a>
		  </div>
		</nav>
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
				{{ message }}
			    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			      <span aria-hidden="true">&times;</span>
			  </button>
			</div>
		{% endfor %}
	{% endif %}
	{% block content %}
	{% endblock %}
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

blog/notes/templates/notes/blog.html
{% extends "notes/base.html" %}

{% block content %}
	<title>{{ blog.title }}</title>
	<h1>{{ blog.title }}</h1>
	<p>{{ blog.pub_date }}</p>
	<p>{{ blog.blog|linebreaks }}</p>
{% endblock %}

blog/notes/templates/notes/index.html
{% extends "notes/base.html" %}

{% block content %}
	<title>{{ blog.title }}</title>
	{% if latest_blog %}
		<ol class="list-group list-group-numbered">
		{% for blog in latest_blog %}
		  <li class="list-group-item d-flex justify-content-between align-items-start">
		    <div class="ms-2 me-auto">
		      <div class="fw-bold"><a href="{% url 'notes:show-details' blog.id %}">{{ blog.title }}</a></div>
		      {{ blog.description }}
		    </div>
		  </li>
		{% endfor %}
	    </ol>
	{% else %}
		<h1>No Blogs Available</h1>
	{% endif %}
{% endblock%}